### ISSUE TITLE
Consider Algolia docsearch

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#128]
Consider using https://community.algolia.com/docsearch/ for site search.

**Comment by rauhs** [comment]
Just wondering, has the clojure site been subitted for indexing to algolia? The actual intregration could then be done by anybody, correct?

**Comment by puredanger** [comment]
We don't have any plans to do this right now.

**Comment by DjebbZ** [comment]
I second this idea. Yesterday I was in Paris (France)'s Algolia offices, and one of the guys told me that since Google is ending soon its Google  Site Search product in April 2018 ([official site](https://enterprise.google.com/search/products/gss.html)). many people will need another solution, which Algolia can provide.

**Comment by puredanger** [comment]
Decided to go with addsearch, now deployed.
