### ISSUE TITLE
Comparators guide

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#15]
Would be cool to see this guide by @jafingerhut turned into a guide: https://github.com/jafingerhut/thalia/blob/master/doc/other-topics/comparators.md

Note: this should only be done with Andy's ok! That's his copyright.

**Comment by jafingerhut** [comment]
Any Clojure contributor has my permission to use any or all of the material in my thalia Github repository and modify it as needed to create submissions for additions to this Github repository.

**Comment by puredanger** [comment]
Thanks Andy!

**Comment by josedonizetti** [comment]
Hey, I've forked the repo and will work on integrating this guide.

**Comment by puredanger** [comment]
Great! I expect the content to live at content/guides/comparators.adoc

**Comment by puredanger** [comment]
Added!

**Comment by jafingerhut** [comment]
@josedonizetti Thanks for the editing work on that article!

A couple of minor formatting issues remain that I noticed -- the list of items under DOs and DO NOTs all become one paragraph with the current markup.

Wherever <= occurs as a symbol in the article, for clojure.core/<=, it shows up as a special combined character rather than the two separate characters < followed by =, which would be clearer in its meaning.

One occurrence of "Firs" should be replaced with "First".

Sorry, I don't know what correct markup syntax is for these things.

**Comment by josedonizetti** [comment]
@jafingerhut Thanks. I'll look into those.

**Comment by puredanger** [comment]
I've got a bunch of formatting edits under way - I will take care of them.
