### ISSUE TITLE
Metadata reader macro documentation is misleading

### ISSUE THREAD

**Issue by czan** [clojure/clojure-site#345]
The "Metadata Reader Macros" section on https://clojure.org/reference/metadata gives a misleading idea of how the `^` syntax actually works. In particular, I think this is misleading:

> * `^{:doc "How obj works!"} obj` - Sets the metadata of obj to the provided map.
>   * Equivalent to `(with-meta obj {:doc "How obj works!"})`

When I read this I thought that it meant that `(def obj {})` followed by `(meta ^{:doc "How obj works!"} obj)` would return `{:doc "How obj works!"}`, when it actually returns `nil`. This is because the reader annotates the source symbol `obj`, which is then dropped by the compiler. This is different to `(meta (with-meta obj {:doc "How obj works!"}))`, which does return `{:doc "How obj works!"}`, as expected.

I think that the line "Equivalent to `(with-meta obj {:doc "How obj works!"})`" should be removed, and a note should be added that it adds metadata to the expression itself, not the value of the expression (and thus is only of value to communicate with the compiler or macros).

**Comment by mars0i** [comment]
Also worth noting that it's incorrect that `^{:doc "How obj works!"} obj`  "Sets the metadata of the obj to the provided map."  The comment implies that the result of the operation is metadata that consists *only* of `{:doc "How obj works!"}`.  In fact `{:doc "How obj works!"}` is merged in with other metadata.

(fwiw, I think this section of this page and the corresponding section of the reader macro page would benefit from one or two short one-line examples of use in context, such as `(def ^{:doc "Canonical punchline."} foo 42)`.)

**Comment by noprompt** [comment]
I agree the first example is misleading. The use of the phrase "equivalent to" is not appropriate for the example provided. We could fix it by replacing `obj` with `'obj` so that it reads

> Equivalent to (with-meta 'obj {:doc "How obj works!"})

However, this would only consider the special case for symbols. If we substitute `obj` with a map or vector the equivalence holds.

```clj
(meta ^{:doc "How obj works!"} [1 2 3])
;; =>
{:doc "How obj works!"}

(meta (with-meta [1 2 3] {:doc "How obj works!"}))
;; =>
{:doc "How obj works!"}
```

So perhaps instead of removing the line, we can append some more information:

* `^{:doc "How obj works!"} obj` - Sets the metadata of `obj` to the provided map.
  * Equivalent to `(with-meta obj {:doc "How obj works!"})` _where `obj` is bound to an object which supports metadata_.

The extra information would ensure the claim of equivalence is true and (hopefully) leave no room for misunderstanding.

**Comment by czan** [comment]
Hey @noprompt, I actually think you've made exactly the mistake that the page leads you towards. Symbols actually aren't a special case for this.

When using `^{:doc "How obj works!"}` you are attaching the metadata to the object literal itself. When you use `[1 2 3]` it happens that the metadata is copied onto the value that's returned, but when you use `'[1 2 3]` that ends up translating to `(quote [1 2 3])`. Thus, `(meta ^{:doc "How obj works!"} [1 2 3])` is `{:doc "How obj works!"}` but `(meta ^{:doc "How obj works!"} '[1 2 3])` is `nil`.

If you look at your final example:
```clojure
(def obj [1 2 3])
(meta ^{:doc "How obj works!"} obj)
;;=> nil
```

Again, the metadata was on the symbol itself, but not the value. The `^` symbol is really about communicating some information to macros, or to the compiler. If you want to add metadata to a value you should use `with-meta`, not the `^` reader.

**Comment by noprompt** [comment]
@czan Perhaps I did a poor job authoring my reply as I understand the semantics of `^` and `with-meta`. The goal of the example is to demonstrate parity between _read-time_ and _run-time_ metadata attachment. I am not mistaken in my remark about symbols being a special case. What I was trying to say is that the documentation _could_ be changed to

> * `^{:doc "How obj works!"} obj` - Sets the metadata of `obj` to the provided map.
>   * Equivalent to `(with-meta 'obj {:doc "How obj works!"})`

to handle that case (note `obj` in the first bullet is not quoted but it is in the second), but should not because it would only consider the case of _literal_ symbols, which would be too narrow in scope (because it is special). To make this clear:

```clj
;; Read-time metadata attachment on symbols
(meta (read-string "^{:doc \"How obj works!\"} obj"))
;; =>
{:doc "How obj works!"}

;; Run-time metadata attachment on symbols
(meta (with-meta 'obj {:doc "How obj works!"}))
;; =>
{:doc "How obj works!"}

;; At read-time 'obj becomes (quote obj) but at run-time it is the symbol obj.
(type (with-meta 'obj {:doc "How obj works!"}))
;; => clojure.lang.Symbol
```

If we want the equivalence claim to hold, at read-time we do not need a quote but at run-time we do i.e. `obj` for read-time, `'obj` for run-time. Also, I forgot to mention that the case for lists is special in this way as well.

The examples you provide with `quote` are correct but they're missing my point about *substitution* in which case I meant _literal_ substitution. Let me clarify by using a similar example as above.

```clj
;; Read-time metadata attachment on vectors
(meta (read-string "^{:doc \"How obj works!\"} [1 2 3]"))
;; =>
{:doc "How obj works!"}

;; Run-time metadata attachment on vectors
(meta (with-meta [1 2 3] {:doc "How obj works!"}))
;; =>
{:doc "How obj works!"}
```

Note in this example `obj` is can be replaced with the same _literal_ in both cases. This will also work for maps and sets.

My suggestion to extend the documentation is to ensure the run-time case is covered such that the claim of equivalence between the read-time expression and the run-time expression is true.

```
;; WRONG! This is not what I'm talking about.
(let [obj 'foo]
  (meta ^{:doc "How obj works!"} obj))
;; =>
nil

;; This is what I'm talking about
;; At read-time
^{:doc "How obj works!"} obj
;; is equivalent to
(let [obj 'foo]
  (with-meta obj {:doc "How obj works!"}))
;; at run-time.
```

By making the documentation clear that `obj` _at run-time_ must be bound to an object that supports meta, the example can hold without the needing to remove it nor would we need to consider quoting.

> The `^` symbol is really about communicating some information to macros, or to the compiler. 

Yes, it is suitable for those goals, however, in general, the `^` _reader_ macro simply attaches metadata to objects read by the _reader_ (provided those objects support metadata). That's it's only purpose. How that metadata is used is not relevant in this discussion because we're talking about semantics.

> If you want to add metadata to a value you should use with-meta, not the ^ reader.

This assertion is context sensitive and depends on which *value* you're referring to it; is it the read-time value or the run-time value?

Considering the read-time versus run-time subtleties, perhaps we should also consider improving the opening paragraph for the section in question.

**Comment by timothypratley** [comment]
FWIW all these examples have been useful to me to better understand these usages of metadata. I think this is a valuable thread and hope a condensed summary can make it into the docs for future reference so I don't have to re-read this thread again *chuckle*. 👍

**Comment by czan** [comment]
> ... I understand the semantics of `^` and `with-meta`. ...

I am confident that we both think this. :stuck_out_tongue: Hopefully eventually we will reach an explanation that we can both agree on.

I do not think it is helpful to consider any cases to be "special" for metadata. You have mentioned lists and symbols as special cases, but in reality the special case for them is in the compiler, not in the metadata reader. For the sake of metadata, they are exactly the same as everything else - it just happens that they evaluate to something that is not themselves. Collection literals, however, evaluate to themselves and thus keep their run-time metadata (which is really the special case for metadata, if you ask me).

> If we want the equivalence claim to hold, ...

I'm not sure that we *need* the equivalence claim to hold. On the one hand, as @mars0i mentioned above, it actually merges the metadata (so anything using `with-meta` is not equivalent); on the other hand, we don't actually need to use `with-meta` (or `vary-meta`, which we should probably mention elsewhere on the page) to explain how the `^` reader works.

Trying to equate the `^` reader with a `with-meta` call is going to cause confusion between read- and run-time, especially because Clojure's reader is not programmable (and thus you can't run code at read-time). The more I think about it, the less I think it's helpful to compare `^` to `with-meta`.

> How that metadata is used is not relevant in this discussion because we're talking about semantics.

Sure, but please understand how terrible that is for new users. We're not writing a specification, we're writing documentation that people learning Clojure will probably read. The page we are discussing isn't purely about semantics. The introduction to the page states "It is used to convey information to the compiler about types, but can also be used by application developers for many purposes, annotating data sources, policy etc.", which is entirely about its use cases, and not the semantics of metadata. A section describing the use cases of the `^` reader would be valuable to this page.

> This assertion is context sensitive and depends on which value you're referring to it; is it the read-time value or the run-time value?

You're right. I have been using unhelpful language out, and have been using "expression" to refer to the read-time value, and "value" to refer to the run-time value. In this message I have tried to be clearer about read- and run-time.

**Comment by noprompt** [comment]
>  You have mentioned lists and symbols as special cases, but in reality the special case for them is in the compiler, not in the metadata reader.

@czan Apologies again, I meant "special" in the case of the example. 😄 

> I'm not sure that we need the equivalence claim to hold... The more I think about it, the less I think it's helpful to compare `^` to `with-meta`.

I've gave this some thought over the weekend and I'm in agreement with you; it's not helpful. My original intention was to try think of ways we could improve the documentation so that we didn't need to eliminate the examples. But, with respect to points brought out in this discussion, I think we should simply truncate the section to read as follows.

> ## Metadata Reader Macros
>
> In addition to `with-meta`, there are a number of reader macros (The Reader: Macro Characters) for applying metadata to the expression following it. For more information on this topic, see the [Metadata (^)](https://clojure.org/reference/reader#_metadata) section.

What do you think?

In addition, I would propose the text at the bottom of the [Metadata (^)](https://clojure.org/reference/reader#_metadata) section

> It is possible to add multiple pieces of metadata by chaining the metadata reader macros together. For example: `^:dynamic ^ints obj` would apply both the `:dynamic` flag and `ints` type-hint to `obj`.

should be merged with the text

> Metadata can be chained in which case they are merged from right to left.

to say (something like)

> Metadata can be chained to add multiple pieces of metadata by chaining the metadata reader macros together. For example: `^:dynamic ^ints obj` would apply both the `:dynamic` flag and `ints` type-hint to `obj`. Metadata chained in this way is merged from right to left.

on that page.

We should also be mindful of @mars0i's remark regarding the merging of metadata as you've suggested and mention that there as well.

**Comment by puredanger** [comment]
Updated here: https://clojure.org/reference/metadata

**Comment by noprompt** [comment]
@puredanger What do you think of truncating the "Metadata Reader Macros" section as I suggested and move the fine details over to the "Reader Macros" section on the page? I see you've added some useful bits of information on this page that would also be useful there. It'd keep all the fine details in one spot and focus this page on just describing the metadata API.

**Comment by puredanger** [comment]
I think both are relevant here, would be fine to duplicate or add a link.

**Comment by puredanger** [comment]
I added a note re metadata chaining right to left. I re-read the reader page and I think what's there is ok as is.
